FROM node:20-alpine AS build

WORKDIR /app

# Force yarn to use npm registry (DNS-safe)
RUN yarn config set registry https://registry.npmjs.org

COPY frontend/package.json frontend/yarn.lock ./

RUN yarn install --frozen-lockfile

COPY frontend/ .
RUN yarn build

FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
